### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by potatogim** [stratis-storage/stratis-docs#119]
IMHO, it can be translated to Korean and that will be helpful for Korean software engineers.

**Comment by agrover** [comment]
Somewhat of a surprising request, I wouldn't have thought the design doc would be that interesting. But hey, yes please, translations in all languages are welcome and we can add links to them on the website.

**Comment by mulkieran** [comment]
We will happily add links to translated documents as they become available. But this doc is still in progress, so probably a while yet.
