### ISSUE TITLE
Create stratis-cli man page

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratis-docs#20]
Create a document to describe the Stratis-cli command-line arguments and options.

**Comment by mulkieran** [comment]
@agrover Didn't we agree that we'ld just go w/ a man-page, at least for the foreseeable future?

**Comment by agrover** [comment]
Yep, I'm working on this so assigning to me.

**Comment by mulkieran** [comment]
I think this is closed by work on stratis-cli.
