### ISSUE TITLE
howto page needs to be updated for init-cache/add-cache changes

### ISSUE THREAD

**Issue by johnsimcall** [stratis-storage/stratis-docs#201]
The [howto page](https://stratis-storage.github.io/howto/) currently advises users to add a cache device to a pool with the deprecated command `stratis pool add-cache 3_amigos /dev/sde`.  The method for initializing and adding cache devices to a pool changed with the [2.1.0 (June 8, 2020) release](https://stratis-storage.github.io/stratis-release-notes-2-1-0/).

> Previously, a cache was initialized as a side-effect of the addition of the first device to the cache tier.

The old instructions should be replaced with new instructions such as `stratis pool init-cache 3_amigos /dev/sde`

**Comment by mulkieran** [comment]
We'll want to fix this in the source.

**Comment by mulkieran** [comment]
@lleshchi Please see what you can do about this. I believe it should be a reasonably quick fix.
