### ISSUE TITLE
Stratis how-to/walk-through - information review request

### ISSUE THREAD

**Issue by samuelfusato** [stratis-storage/stratis-docs#238]
Hi,

I was reading [this](https://stratis-storage.github.io/howto/) tutorial about Stratis storage management and would like to confirm the "Add mount point to /etc/fstab using file system UUID" part about the following entry:

```
echo "UUID=a38780e5-04e3-49da-8b95-2575d77e947c /mnt xfs defaults 0 0" >> /etc/fstab
```

This will not work on RHEL8 and the machine will fail to start. It is missing the ```x-systemd.requires=stratisd.service``` mount option, that is:

```
UUID=a38780e5-04e3-49da-8b95-2575d77e947c /mnt xfs defaults,x-systemd.requires=stratisd.service 0 0
```
Can you kindly confirm?

Thanks.

**Comment by jbaublitz** [comment]
Hi @samuelfusato! Can you give me a little bit more information?

First off, what version of stratisd are you using? Secondly, is this filesystem on an encrypted pool?

If you are using stratisd version 2.4.0 or later, I would recommend reading the following blog post:

https://stratis-storage.github.io/stratis-rootfs/

This blog post not only outlines using Stratis filesystems as the root filesystem but also support for non-root filesystems in /etc/fstab. My guess is that your entry should either be:

```
UUID=a38780e5-04e3-49da-8b95-2575d77e947c /mnt xfs defaults,x-systemd.requires=stratis-fstab-setup@[POOL_UUID],x-systemd.after=stratis-fstab-setup@[POOL_UUID] 0 0
```
or
```
UUID=a38780e5-04e3-49da-8b95-2575d77e947c /mnt xfs defaults,x-systemd.requires=stratis-fstab-setup@[POOL_UUID],x-systemd.after=stratis-fstab-setup@[POOL_UUID],nofail 0 0
```
depending on whether the pool is encrypted, whether you want the boot to wait until this filesystem is mounted, and a few other considerations outlined in the blog post.

Please let me know if you have any additional questions!
