### ISSUE TITLE
Document external users of Stratis on Stratis website

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-docs#248]

**Comment by mulkieran** [comment]
We can follow the hypothesis model, or something like it: https://hypothesis.readthedocs.io/en/latest/strategies.html.

**Comment by mulkieran** [comment]
@drckeefe If you want to put a starter list in the comments, feel free. Once we have a few items, we can go ahead, put up a page, and encourage other users to submit PRs as appropriate.

**Comment by drckeefe** [comment]
Here are a few items:
Projects:
Cockpit - https://cockpit-project.org/blog/cockpit-256.html
Blivet - https://github.com/storaged-project/blivet-gui/pull/277, https://github.com/storaged-project/blivet/pull/952
BOOM - https://github.com/snapshotmanager/boom/blob/8d377444b1f3a3efb636270cc0963f420ee1fdb9/boom/stratis.py
Munin -https://gallery.munin-monitoring.org/plugins/munin-contrib/stratis/

Operating System Availability: 
Fedora - stratisd, stratis-cli RPMs
Red Hat - stratisd, stratis-cli RPMs
Arch Linux - https://archlinux.org/packages/community/x86_64/stratisd/

Future Projects
Anaconda 
CoreOS

**Comment by drckeefe** [comment]
Looking at the Hypothesis site, the list and links for Stratis might be better represented as: 

Stratis can be found in the following OSs
Fedora -   https://getfedora.org/
Red Hat - https://redhat.com/
Arch Linux - https://archlinux.org/

Projects that have Stratis support
Cockpit - https://github.com/cockpit-project/cockpit
Blivet - https://github.com/storaged-project/blivet/
BOOM - https://github.com/snapshotmanager/boom
Munin - https://gallery.munin-monitoring.org/

**Comment by mulkieran** [comment]
Ok! We've got a good list, but putting this in will require some web design stuff.
