### ISSUE TITLE
Intro Request on landing page

### ISSUE THREAD

**Issue by erikbgithub** [stratis-storage/stratis-docs#257]
Hi, could you add an intro to the top of your website that is like the executive summary in the latex document?

copy&paste:

```
Stratis is a new tool that meets the needs of Red Hat Enterprise Linux (RHEL) users (among
others) calling for an easily configured, tightly integrated solution for storage that works within
the existing Linux storage management stack. To achieve this, Stratis prioritizes a straightforward
command-line experience, a rich API, and a fully automated, externally-opaque approach to
storage management. It builds upon elements of the existing storage stack as much as possible,
to enable delivery within 1-2 years. Specifically, Stratis initially plans to use device-mapper and
the XFS filesystem, but may incorporate other technology in the future
```

And below maybe 2-5 lines of shell code that show how it adds value?

Reason for asking: When I google for stratis storage, that is the first page that comes up. And if they are not as excited as me about RHEL tooling they might simply leave again as the page doesn't explain what the tool actually is.

Happy to help implement this, if desired.

**Comment by mulkieran** [comment]
I'll consider this resolved by #255.
