### ISSUE TITLE
Need better documentation for the project API

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-docs#3]
There are madly out of date and will be very hard to maintain.

It might make sense to dump in the current, most up-to-date introspection information, and then maybe have a little further information about princiiples, if any.

Demo of this approach now available in docs.

**Comment by mulkieran** [comment]
It is probably not a bad idea to dump the CLI usage examples, as well. They are out of date, will also be hard to maintain, are very incomplete, etc.

**Comment by agrover** [comment]
we could think about better homes, maybe the user guide for the cmdline stuff, maybe an API reference for the DBus stuff?

**Comment by mulkieran** [comment]
Absolutely. And those are both good locations.

**Comment by mulkieran** [comment]
Note that documentation in the source code would be some sort of step toward this goal. Also, note that at this time, even though a few of the methods in the source code are commented using the appropriate format I have yet to get any of this to show up using "cargo doc".

**Comment by mulkieran** [comment]
The API stuff in the Design Doc was cleared out by commit #12.
