### ISSUE TITLE
Cache a built version of zola for CI

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-docs#302]
We could maybe use a containerized zola, or we could find some way that GitHub can cache the built zola between runs of our CI. It builds just fine in our CI, but it takes a mighty long time.

**Comment by jbaublitz** [comment]
I am more partial towards containerized Zola.

**Comment by mulkieran** [comment]
https://www.getzola.org/documentation/getting-started/installation/#docker is info about docker zola container. It's supported by the zola project, so we should expect it to be reliable.

**Comment by mulkieran** [comment]
We install zola from COPR for our CI, so this is no more.
