### ISSUE TITLE
We need to determine whether integer is really a valid JSON type

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-docs#31]
Some documents seem to say that it is, and other's disagree. It may be a question of the particular version of the spec.

**Comment by mulkieran** [comment]
We no longer provide a schema in our design docs. In future, we may use one for testing, and we can handle this problem then.

**Comment by jbaublitz** [comment]
@mulkieran Just a note that this RFC does claim it is a valid type: https://tools.ietf.org/html/rfc7159#section-6. There is a lot of variation between JSON implementations however so that may be the problem.
