### ISSUE TITLE
CoW?

### ISSUE THREAD

**Issue by wyoung** [stratis-storage/stratis-docs#51]
I infer by your use of XFS that Stratis does not support copy-on-write today, one of the key advantages of ZFS and btrfs relative to the current RHEL storage stack, being the near-manual LVM2 + MD + XFS lash-up.

I understand that CoW-on-XFS is [coming](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0cbbc422d56668528f6efd1234fe908010284082) in some unspecified future version of XFS.

I would like the document to clarify this situation:

1. State that CoW-on-XFS is expected to arrive sometime during the Stratis development plan, and say which versions are expected to coincide. That is, will we have it for Stratis 1.0, 2.0, 3.0...?

2. If you cannot make such a claim, this should be called out in the document as a known limitation of Stratis relative to ZFS and btrfs.

**Comment by agrover** [comment]
Stratis supports CoW by using dm-thin. https://www.kernel.org/doc/Documentation/device-mapper/thin-provisioning.txt

**Comment by wyoung** [comment]
While it is good to have this question answered in the Issues list, it still needs to be answered in the doc, since that will be a primary reference point for people comparing ZFS or btrfs to Stratis.

**Comment by agrover** [comment]
Where in the doc? The doc discusses thin provisioning and snapshots, which are closely associated with CoW. Do we just need to say "CoW" or "copy-on-write" somewhere so that people know that's what we're talking about, or something more?

**Comment by wyoung** [comment]
Yes, please add "CoW" *and* "copy-on-write" somewhere in there, if only for people who are only willing to hit Ctrl-F and type a few keywords.

Better, add a table comparing ZFS, btrfs, Stratis 0.1, 0.5, 1.0, and 2.0 at least, preferably near the top of the doc.
