### ISSUE TITLE
SMART

### ISSUE THREAD

**Issue by wyoung** [stratis-storage/stratis-docs#52]
The documentation talks about the `stratisd` monitoring daemon but does not talk about SMART at all. Will `stratisd` functionally replace `smartd`? 

For example, is `stratisd` expected to make a decision about a rapidly-climbing reallocated sector count on a drive and mark the drive as troubled, maybe even automatically swap in a spare when that functionality lands?

**Comment by agrover** [comment]
Yes this is an open question, see https://github.com/stratis-storage/stratisd/issues/72.
