### ISSUE TITLE
Filesystem awareness

### ISSUE THREAD

**Issue by wyoung** [stratis-storage/stratis-docs#53]
One of the limitations of the current LVM2 + XFS or MD + XFS lash-ups is that the block layer cannot talk up the stack to the filesystem, and the filesystem treats the block layer as a dumb pile of storage.

I'm not familiar with btrfs in this respect, but with ZFS, one of the huge advantages you get from a unified filesystem and volume manager is that when all redundant copies of a given block are unreadable or corrupt, it doesn't just mark the pool as degraded and demand a disk swap. Instead, it tells you exactly which file is affected. If you remove or replace that file, the problem instantly goes away, because those damaged blocks are no longer involved with that file.

This is partly thanks to CoW, but independent of it, since even in a filesystem that overwrites blocks in place, that overwrite operation may be able to repair the damage. If it's just soft corruption, simply overwriting the blocks fixes it. If it's on-rust corruption, the drive's sector remapper is likely to swap in a fresh sector when the write occurs, and if not, the filesystem can potentially react to a failed write and mark that sector out in the same way `badblocks` does.

Will Stratis have this tight interoperation between the filesystem and the block layer, or will the fact that it is built atop several "foreign" code bases mean it will remain unable to diagnose and repair itself in the way ZFS can?

**Comment by agrover** [comment]
What Stratis will be able to do is detect on-disk corruption on reads by using dm-integrity. This could be recoverable if there's redundancy (Stratis 2.0). If not, Stratis should still be able to convert the bad block to the file -- XFS added reverse-mapping support in kernel 4.8. There may be API work needed at either the fs or dm-thin level --I haven't looked -- to walk up the stack but I think the raw info is there.
