### ISSUE TITLE
Details about XFS Shrinking Support 

### ISSUE THREAD

**Issue by mbukatov** [stratis-storage/stratis-docs#57]
[XFS doesn't support shrinking](http://xfs.org/index.php/Shrinking_Support) at the moment. And in the design  document, you state that:

> Stratis requires the filesystem used have online resize (or at least online
grow) capabilities

Would it make sense to explain in more detail why lack of shrinking is not a problem for Stratis? As I went through the design document, it seems that Stratis would grow the filesystem automatically while removing block devices would be supported.

## References

https://github.com/stratis-storage/stratis-docs/blob/2dfbb8438f4a405a4151f25374bfab53d9d8f0f3/docs/design/StratisSoftwareDesign.lyx#L734

**Comment by agrover** [comment]
In the absence of shrink, Stratis can't reduce the filesystem's virtual size, but it can reclaim unused space by using trim, achieving the same goal. How about if we add something like this?

>To meet the goal of eliminating manual filesystem resizing by the user, Stratis requires the filesystem used have online resize (or at least online grow) capabilities, which XFS does. In the absence of online shrink, Stratis would rely on trim to reclaim space from an enlarged but mostly empty filesystem, and return it to the thin pool for use by other filesystems.

**Comment by mbukatov** [comment]
Yes, this makes it clear.
