### ISSUE TITLE
How does Stratis relate to storaged/udisks?

### ISSUE THREAD

**Issue by mbukatov** [stratis-storage/stratis-docs#58]
I see that [storaged](http://storaged.org/) is mentioned in [stratis-interactions.svg diagram](https://github.com/stratis-storage/stratis-docs/blob/master/docs/design/stratis-interactions.svg), where it uses Stratis D-Bus API, but there is no other explanation of how storaged relate to Stratis in the document.

Do I understand it right that you expect Storaged/udisks to implement support for Stratis managed storage for Cockpit, Gnome and other components which uses storaged? Moreover since Storaged is a daemon which provides D-Bus API, would it make sense to compare it's design with Stratis?

**Comment by agrover** [comment]
How does storaged interact with ZFS or Btrfs? That's how Storaged would interact with Stratis, except that Stratis makes it easier by providing an actual API. Storaged can make calls to other D-Bus APIs in addition to providing its own.
