### ISSUE TITLE
Generate & post HTML version of latest docs

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratis-docs#6]
We've chosen to use LyX to generate our design doc and to-be-written user's guide, but we want to make these easily readable via HTML. One possible way might be to generate HTML output off of a commit hook, and then publish them to our project's GitHub Pages (see https://pages.github.com/), and then point people there in the README.md or from wherever.

In moving away from Google Docs, we also have lost its nifty comment-adding feature. We should document what readers should do if they have comments or questions about our docs. (I guess open an issue?)

**Comment by mulkieran** [comment]
We should probably use our _Organization_'s pages to publish these docs.

**Comment by mulkieran** [comment]
They can add them as notes in the project tab?

**Comment by mulkieran** [comment]
What we want to do is:
1. On a merge to stratis-docs
2. Clone the stratis-docs repo
3. Run "make website" to make the website, whatever it amounts to
4. Clone the stratis-storage.github.io repo.
5. Clear all files out of that repo
6. Copy built website from stratis-docs repo to stratis-storage.github.io repo, and push these changes.

It is not clear to me how we can do that so easily with webhooks and what not. It might go easier with a cron job.

Or, we can get away from using GitHub for our site and post it somewhere on some RH pages? That would be in some sense easier. We still need to clone and build the website from the stratis-docs repo,
but we don't have to mess with the github.io repo.
