### ISSUE TITLE
Design doc: questions/clarifications

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratis-docs#64]
* 10.2.5 *Progressively throttling writes*, is this implemented? 

* 10.2.7 Will Stratis support changing the pass phrase for a Snapshot of an 
encrypted FS?

* 10.2.8 What if a FS has no idle periods, will stratis eventually force a 
fstrim or will the fstrim starve?  Will dm stats be used for the historical 
system I/O activity levels?

* 10.3.4 Should the BDA format include a version field?
Note: It would be good to have a little more detail on the write sequence when
multiple devices exist.  More detail on the algorithm would be helpful.

* 10.3.5 Should the MDA JSON format include a version field?

* 10.3.7 Would it be useful to have a background or periodic task that updates 
the physical device(s) meta data to make them current?  When a box comes up with 
the current design you are required to read every physical disk to ensure you have 
found the latest metadata, correct?

**Comment by agrover** [comment]
> 10.2.5 Progressively throttling writes, is this implemented?

No. issue [here](https://github.com/stratis-storage/stratisd/issues/313).

> 10.2.7 Will Stratis support changing the pass phrase for a Snapshot of an
encrypted FS?

Probably, but it's still TBD. We haven specc'd out encryption support yet, it's currently not until Stratis 3.

> 10.2.8 What if a FS has no idle periods, will stratis eventually force a
fstrim or will the fstrim starve? Will dm stats be used for the historical
system I/O activity levels?

TBD. I don't know how aggressive we want to go here -- we only really need to fstrim when we need to reclaim unused space from a fs for another fs.

Yes probably dmstats would be easiest to get this info.

> 10.3.4 Should the BDA format include a version field?

We have a currently-unused flags field that could be possibly used for indicating support for added features. We also have a lot of unused bytes that we could carve a version field from if needed.

> 10.3.5 Should the MDA JSON format include a version field?

If eventually needed, it might be cleaner to have the variable-length format metadata in the BDA or MDA region header, so one doesn't have to parse it to figure out if it's a known version. 

> 10.3.7 Would it be useful to have a background or periodic task that updates
the physical device(s) meta data to make them current? When a box comes up with the current design you are required to read every physical disk to ensure you have found the latest metadata, correct?

That's correct, but how would updating all blockdevs avoid the full scan?

**Comment by tasleson** [comment]
>That's correct, but how would updating all blockdevs avoid the full scan?

True this doesn't alleviate the full scan.

I was thinking more of the case where you have a large number of devices and you write to the first six for example (doc mentions you don't have to write to all).  Then some time later you take a power hit, box comes back up but those 6 disks happen to be in the same JBOD which doesn't come back online.  What happens now?  It's not apparent to me from the documentation.

**Comment by agrover** [comment]
Ah ok I get more what you're saying. That is a bad situation. The doc talks a little about picking blockdevs for path diversity (or randomly) to avoid this but we probably want to expand on this in the doc for all combinations of:
* The reason why the metadata changed (blockdev add or remove, flex-layer device was extended/moved, user_info changed)
* number of blockdevs written with updated metadata before power hit (0, 1, x, all)

and determine the right thing to do regarding:
* ordering of DM operations before or after writing the new metadata
* actions: proceed with stale metadata? fail pool activation if missing any members? or maybe fail activation only if missing any in-use members?

BTW supporting writing updated metadata to a subset of blockdevs is really not something we need in the near future. Blockdev metadata will not change that often, and given that, even writing it to many blockdevs -- even 256? -- might be ok. But even with a write-all-blockdevs policy, I think we will need to work through and consider the cases above, before we can have confidence in Stratis.

**Comment by mulkieran** [comment]
>> 10.3.5 Should the MDA JSON format include a version field?

> If eventually needed, it might be cleaner to have the variable-length format metadata in the BDA or MDA region header, so one doesn't have to parse it to figure out if it's a known version. 

You mean the variable-length format metadata _version_. It would be a good idea to have a version, so we can avoid a strategy of making values optional because we think we might in future drop them from the metadata.

**Comment by mulkieran** [comment]
Obsoleted by design doc clean-up.
