### ISSUE TITLE
DBUS API Doc:  questions/clarifications

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratis-docs#65]
#### General

* Potentially long running operations, eg. creating **many** filesystems in 
one call.  How sure are we that the method will complete
before the timeout between the client and service expires?  Or is the client 
to set the dbus client timeout to infinity?

* When you supply a list of things to be created, what happens if some are 
successful and some fail?  eg. CreateFileSystems, DestroyFileSystems?  Or is the
contract all or none?

* Clarification, if you repeatedly set the name of a resource to the same name,
is the result = False, 0, "" ?

#### Specific
* 1.1.2  Typically in dbus calls to provide for an optional argument you use a 
hashmap, so that the existence of the key indicates it's presence and of course
it's associated value.  What is the convention if a method takes an optional 
argument for the value of the second argument to be even though it's to be 
ignored?

* 3.0 Would it be better to be consistent with the return value being always 
in element 0, message in element 1 and then the result in element 2 if 
present.  Perhaps I'm missing a benefit to utilizing the documented approach.

**Comment by agrover** [comment]
General
* as we talked about on irc, hopefully there wouldn't be any long-running operations, but if there were we'd tackle that issue when it arose
* an array is returned with the successfully created (or destroyed) things, and then it's up to the client.
* correct

Maybe @mulkieran or @trgill can answer the other parts? I don't have a ready answer to these...

**Comment by mulkieran** [comment]
My answer to 3.0 is that I doubt that it matters much either way.

**Comment by mulkieran** [comment]
My answer to 1.1.2. I think you're talking about the situation of our redundancy argument to ```create_pool```. We use a tuple in that case, where the first item is a boolean and the second is an item of the correct type.

**Comment by tasleson** [comment]
> My answer to 1.1.2. I think you're talking about the situation of our redundancy argument to create_pool. We use a tuple in that case, where the first item is a boolean and the second is an item of the correct type.

I understand what you are doing, my question is that when the first argument of the tuple is False, the second parameter doesn't matter, but from an dbus API usage it must have a value of the correct type.  
Any suggested value to represent that which is to be ignored?  Yes the value doesn't matter, but for example the accepted dbus convention is that to pass an empty object path one uses a '/' for the object path as you cannot pass an empty string for an object path.

This is one reason I like just passing a hashmap for optional arguments.  The additional benefit is you can extend an existing API call without breaking API compatibility or introducing a new method call.  Some would argue this is an escape hatch of sorts, but it works :-)

**Comment by tasleson** [comment]
> My answer to 3.0 is that I doubt that it matters much either way.

When using an API I think it's nice to have consistency, (eg. result code always in element 0), bikeshedding would be easy here, so I'll defer raising this as an issue if no one else feels strongly about it.

**Comment by mulkieran** [comment]
>> My answer to 3.0 is that I doubt that it matters much either way.

> When using an API I think it's nice to have consistency, (eg. result code always in element 0), bikeshedding would be easy here, so I'll defer raising this as an issue if no one else feels strongly about it.

I think we have an equal amount of consistency either way. But it's true that our current consistency is more mathematically sophisticated. I think it hasn't bothered us, because we use tuples to extract the values in the Python code. If you were to implement a more mathematically unsophisticated consistency, I would not object.

**Comment by mulkieran** [comment]
> > My answer to 1.1.2. I think you're talking about the situation of our redundancy argument to create_pool. We use a tuple in that case, where the first item is a boolean and the second is an item of the correct type.

> I understand what you are doing, my question is that when the first value of the tuple is False, the second parameter doesn't matter, but from a dbus API usage it must have a value of the correct type.  
Any suggested value to represent that which is to be ignored?  Yes the value doesn't matter, but for example the accepted dbus convention is that to pass an empty object path one uses a '/' for the object path as you cannot pass an empty string for an object path.

> This is one reason I like just passing a hashmap for optional arguments.  The additional benefit is you can extend an existing API call without breaking API compatibility or introducing a new method call.  Some would argue this is an escape hatch of sorts, but it works :-)

I think defaults are just really easy to come up with, so that wasn't a worry. We have to come up with them in our stratisd code and we do not fail.

**Comment by agrover** [comment]
@tasleson any outstanding issues or questions left, or can we close this issue?

**Comment by tasleson** [comment]
I've voiced my concerns with the existing API  and that we are making the decision to ignore the advice of others on best practices.  I said my piece.
