### ISSUE TITLE
Need a discussion/justification of udev use in design doc

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-docs#75]

**Comment by mulkieran** [comment]
The reason for all this is that we want to explain when we expect udev to be available, why we choose to use it rather than something else to detect information about devices, and whatever else is relevant.

**Comment by agrover** [comment]
Oops, didn't mean to push 3ad17d8 to master just yet. Umm, if you want, please take a look at that commit and reopen this if needed. :frowning:
