### ISSUE TITLE
style guide: Python

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-docs#78]
* Use list comprehensions instead of for-loops. for-loops are super-general, obviously, while list comprehensions are more restricted. This makes list-comprehensions clearer in the case where they can be used at all.
* Do not use boolean overloading in if conditions unless it is the case that the type of the object is unknown. If the type of the object is known, then do an explicit comparison as ```is None```, ```== []```, etc. This way, when an object of an unexpected type arrives, you get a failure at the comparison, not a subtle bug which may hang around for literally years before being discovered.
* Use os.path methods when assembling or deconstructing paths. This is just for clarity, to make it clear that it's a path, not a string that is being manipulated. It would be important if we were cross-platform, which we are not.

**Comment by tasleson** [comment]
Add pep8 formatting
