### ISSUE TITLE
DBUS: Documentation and implementation for blockdev do not agree

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratis-docs#95]
* Properties
  * `State` listed as a `s`, it is actually a `q` or `uint16`
  * `InitializationTime` documented as a `s` string, it's actually a `t` or `uint64`
  * `Tier` not documented, currently it is a `q`

* Method
  * `SetUserId` is actually `SetUserInfo`

**Comment by mulkieran** [comment]
Or possibly the code is incorrect.
